### ISSUE TITLE
Missing Cartfile?

### ISSUE THREAD

**Issue by AndreasPaulsson** [NAXAM/izettle-ios-binding#4]
Hi, I am trying to upgrade this project to SDK 3.7.0.

But I get stuck on the first part:  "1. Update Cartfile with the desired version" since there is no Cartfile in the repo.

Should I create a new Cartfile or is it just missing?

I am a pretty experienced .NET developer (20 years) but I have never worked with Carthage or sharpie before so I apologise in advance if I am asking stupid questions.

**Comment by AndreasPaulsson** [comment]
I just saw that you are currently updating to SDK 3.7.0, that is great! 

Do you have a publish date to nuget?

Please tell me if there is anything that I can do to help, I am very eager to test.

**Comment by tuyen-vuduc** [comment]
Hi @AndreasPaulsson Thanks for your interest at my library. The cartfile is no longer needed. I forgot to update the readme.

Please check out [the latest version on Nuget then](https://www.nuget.org/packages/Naxam.iZettle.iOS/3.7.0.1).

If you find it helpful, please share me a cup of coffee then.

[!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/tuyen.vuduc)

I am also looking for a sponsor to do the Android part as well.
